export const RECEIVE_BROADCAST_SLOTS = 'RECEIVE_BROADCAST_SLOTS';
export const REQUEST_BROADCAST_SLOTS = 'REQUEST_BROADCAST_SLOTS';
export const FAILED_FETCH_BROADCAST_SLOTS = 'FAILED_FETCH_BROADCAST_SLOTS';

export const SET_CHANNELS = 'SET_CHANNELS';
export const SET_SLOT = 'SET_SLOT';
export const UNSET_SLOT = 'UNSET_SLOT';